build:
    environment:
        php:
            version: 7.2
        postgresql: false
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
checks:
    php: true
filter:
    excluded_paths:
        - "tests/*"
        - "vendor/*"
        - "examples/*"
        - "benchmark/*"
